# fly.toml app configuration file generated for pocketbase-sveltekit-starter-bitter-glade-7537-summer-shadow-1313 on 2024-03-07T00:51:57-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocketbase-sveltekit-starter-bitter-glade-7537-summer-shadow-1313'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
